spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath*:com/gpmall/pay/dal/persistence/*Mapper.xml"
  type-aliases-package: com.gpmall.pay.dal.entitys

ali:
  ali_service: 
  ali_partner:  
  input_charset: utf-8
  sign_type: MD5
  notify_url: http://shop.gupaoedu.com/pay/alipayNotify
  return_url: http://shop.gupaoedu.com/pay/syncResult
  seller_id:  
  seller_email: 
  pay_gateway_new: https://mapi.alipay.com/gateway.do?
  it_b_pay: 1h
  private_key: 
  public_key: 
  pay_open_gateway: https://openapi.alipay.com/gateway.do
  #退款接口名
  refund_service: refund_fastpay_by_platform_pwd
  #退款通知回调地址
  refund_notify_url: http://shop.gupaoedu.com/refund/alipayRefundNotify

wechat:
  wechat_appid: 1
  wechat_mch_id: 1
  wechat_appsecret: 1
  wechat_mchsecret: 1
  wechat_notifyurl: http://shop.gupaoedu.com/pay/wechatPayNotify
  wechat_unified_order: https://api.mch.weixin.qq.com/pay/unifiedorder
  wechat_order_query: https://api.mch.weixin.qq.com/pay/orderquery
  #申请退款url
  wechat_refund_url: https://api.mch.weixin.qq.com/secapi/pay/refund
  #退款通知回调地址
  wechat_refund_notify_url: https://fada6b7e.ngrok.io/refund/wechatRefundNotify




