spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:com/gpmall/user/dal/persistence/*Mapper.xml"
  type-aliases-package: com.gpmall.user.dal.entitys

mapper:
  mappers: com.gpmall.user.config.MyMapper
  not-empty: false
  identity: MYSQL