
export const apis = {
  userLogin: '/user/login',
  loginOut: '/user/loginOut',
  userInfo: '/user/login',
  register: '/user/register',
  upload: '/user/imgaeUpload',
  updateheadimage: '/user/updateheadimage',
  productHome: '/shopping/homepage',
  navList: '/shopping/navigation',
  recommend: '/shopping/recommend',
  getAllGoods: '/shopping/goods',
  getAllCategories: '/shopping/categories',
  getCartList: '/shopping/carts',
  addCart: '/shopping/carts',
  delCart: '/shopping/carts',
  delCartChecked: '/shopping/items',
  cartEdit: '/shopping/carts',
  editCheckAll: '/shopping/items',
  cartDel: '/shopping/carts',
  addressList: '/shopping/address',
  getAddress: '/shopping/address',
  addressUpdate: '/shopping/updateAddress',
  addressAdd: '/shopping/addAddress',
  addressDel: '/shipping/delAddress',
  submitOrder: '/shopping/order',
  payMent: '/cashier/pay',
  orderList: '/shopping/order',
  getOrderDet: '/shopping/order',
  cancelOrder: '/shopping/cancelOrder',
  productDet: '/shopping/product',
  delOrder: '/shopping/delOrder',
  getSearch: '/shopping/search',
  getQuickSearch: '/goods/quickSearch'
}
