
export const apis = {
  userLogin: '/user/login',
  loginOut: '/user/loginOut',
  userInfo: '/user/login',
  register: '/user/register',
  upload: '/user/imgaeUpload',
  updateheadimage: '/user/updateheadimage',
  productHome: '/shopping/homepage',
  // 导航栏
  navList: '/shopping/navigation',
  // 推荐商品
  recommend: '/shopping/recommend',
  // 获取产品列表
  getAllGoods: '/shopping/goods',
  // 产品分类
  getAllCategories: '/shopping/categories',
  // 商品评论
  getAllComments: '/shopping/comments',
  // 商品评论数量
  getAllCommentsCount: '/shopping/comment/count',
  getCartList: '/shopping/carts',
  addCart: '/shopping/carts',
  delCart: '/shopping/carts',
  delCartChecked: '/shopping/items',
  cartEdit: '/shopping/carts',
  editCheckAll: '/shopping/items',
  cartDel: '/shopping/carts',
  addressList: '/shopping/addresses',
  getAddress: '/shopping/addresses',
  addressUpdate: '/shopping/addresses',
  addressAdd: '/shopping/addresses',
  addressDel: '/shopping/addresses',
  submitOrder: '/shopping/order',
  payMent: '/cashier/pay',
  orderList: '/shopping/order',
  getOrderDet: '/shopping/order',
  cancelOrder: '/shopping/cancelOrder',
  productDet: '/shopping/product',
  delOrder: '/shopping/delOrder',
  getSearch: '/shopping/search',
  getQuickSearch: '/shopping/search'
}
